---
- hosts: all, !unprovisioned
  vars:
    apt_deps:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl

  tasks:
  - name: Install dependency packages for adding HTTPS repos
    become: yes
    apt:
      name: "{{ apt_deps }}"

  - name: Add official docker repo key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    
  - name: Add docker repo
    become: yes
    apt_repository: 
      repo: deb [arch=armhf] https://download.docker.com/linux/debian "{{ ansible_distribution_release }}" stable
      state: present
      update_cache: yes
  
  - name: install docker & docker compose
    become: yes
    apt:
      name: "docker-ce docker-compose"
  